[root@k8s-lab2-master-1 mis-homepage]# cat mis-homepage-deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mishomepage
  namespace: mishomepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mishomepage
  template:
    metadata:
      annotations:
        # 更新 version 觸發重新部署
        config-hash: "v6"
      labels:
        app: mishomepage
    spec:
      serviceAccountName: homepage-admin # 讓 Pod 具備 homepage-admin 的權限 ---
      containers:
      - name: mishomepage
        image: ghcr.io/gethomepage/homepage:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: HOMEPAGE_ALLOWED_HOSTS
          value: "*"
        # --- 解決 500 Error 的核心關鍵：忽略自簽憑證驗證 ---
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
        volumeMounts:
        # --- 設定檔掛載 (ConfigMap) ---
        - name: mis-config-volume
          mountPath: /app/config/settings.yaml
          subPath: settings.yaml
        - name: mis-config-volume
          mountPath: /app/config/services.yaml
          subPath: services.yaml
        - name: mis-config-volume
          mountPath: /app/config/widgets.yaml
          subPath: widgets.yaml
        - name: mis-config-volume
          mountPath: /app/config/bookmarks.yaml
          subPath: bookmarks.yaml
        - name: mis-config-volume
          mountPath: /app/config/custom.yaml
          subPath: custom.yaml
        - name: logs-volume
          mountPath: /app/config/logs
      volumes:
      - name: mis-config-volume
        configMap:
          name: mis-homepage-config
      - name: logs-volume
        emptyDir: {}

