apiVersion: apps/v1
kind: Deployment
metadata:
  name: mishomepage
  namespace: mishomepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mishomepage
  template:
    metadata:
      annotations:
        config-hash: "v23" # 確保 apply 時會重新觸發 Pod
      labels:
        app: mishomepage
    spec:
      serviceAccountName: homepage-admin # 這是關鍵，必須對應有權限的 SA
      containers:
      - name: mishomepage
        image: ghcr.io/gethomepage/homepage:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: HOMEPAGE_ALLOWED_HOSTS
          value: "*"
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
        volumeMounts:
        - name: mis-config-volume
          mountPath: /app/config/settings.yaml
          subPath: settings.yaml
        - name: mis-config-volume
          mountPath: /app/config/services.yaml
          subPath: services.yaml
        - name: mis-config-volume
          mountPath: /app/config/widgets.yaml
          subPath: widgets.yaml
        - name: mis-config-volume
          mountPath: /app/config/bookmarks.yaml
          subPath: bookmarks.yaml
        - name: mis-config-volume
          mountPath: /app/config/custom.yaml
          subPath: custom.yaml
        # 強制掛載 kubernetes.yaml 避開自動生成機制
        - name: mis-config-volume
          mountPath: /app/config/kubernetes.yaml
          subPath: kubernetes.yaml
        - name: logs-volume
          mountPath: /app/config/logs
      volumes:
      - name: mis-config-volume
        configMap:
          name: mis-homepage-config
      - name: logs-volume
        emptyDir: {}
