apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: homepage-k8s-full-reader
rules:
  - apiGroups: ["", "metrics.k8s.io"]
    resources: ["nodes", "pods", "namespaces", "nodes/metrics", "nodes/proxy"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: homepage-k8s-full-reader-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: mishomepage
  # 萬一你的 Pod 其實是跑在別的 SA 下，我們把 system:serviceaccounts 也加進去測試
  - kind: Group
    name: system:serviceaccounts:mishomepage
roleRef:
  kind: ClusterRole
  name: homepage-k8s-full-reader
  apiGroup: rbac.authorization.k8s.io
